- 1. 


What will the following code output?

There is 1 correct answer



try {
int[] arr = new int[5];
arr[10] = 100;
System.out.println("Inside try block");
} catch (ArrayIndexOutOfBoundsException e) {
System.out.println("Exception caught");
} finally {
System.out.println("Finally block executed");

}


Inside try block
Exception caught
Finally block executed
- [x]  Exception caught, Finally block executed
Inside try block, Exception caught, Finally block executed
Inside try block, Finally block executed


_____________________________________________________________________________________
- 2. 


Which of the following Java code snippets contains a syntax error?

A) int x = 100;
B) double rate = 0.1;
C) String message = ‘Hello, world!’;
D) float y = 20.0f;
E) boolean isJavaFun = true;
F) char option = “A”;

There are 2 correct answers

- [x] C
A
B
- [x] F
E
D




_____________________________________________________________________________________


- 3. 


In Java, is it always necessary for a try block to be followed by either a catch block or a finally block?
The are 1 correct answers

Correct
- [x] Incorrect



_____________________________________________________________________________________


- 4. 

Given the following code fragment, what is the result?

The are 1 correct answers


public static void main(String[] args) {

int[] arr = {10,0};
int i = 0;

try {
int answer = arr[i] / arr[i + 1];
} catch (Exception e) {
System.out.println("Unknown issues.");
} catch (ArithmeticException ae) {
System.out.println("Invalid divisor");

}

}

Unknown issues.
Invalid divisor.
Unknown issues.
Invalid divisor.
- [x]  A compilation error occurs


_____________________________________________________________________________________

- 5. 

Which exception is thrown by the following code snippet?

int[] arr = {1, 2, 3};
int value = arr[5];

There is 1 correct answer

ArithmeticException
- [x]  ArrayIndexOutOfBoundsException
IndexOutOfBoundsException
NumberFormatException
ArrayOutOfBoundsException





_____________________________________________________________________________________

- 6. 
Can we have multiple catch blocks in Java?
The are 1 correct answers

- [x]  Correct
Incorrect


_____________________________________________________________________________________


- 7. 

State whether the below statement is Correct or Incorrect. An exception generated by a try block is caught by the catch block?
The are 1 correct answers

Incorrect
- [x] Correct


_____________________________________________________________________________________


- 8. 

Given the following code fragment, what is the result?

The is 1 correct answer

int number = 1;
String s = null;

try {
number = s.length();
number += 2;
} catch (RuntimeException e) {
number += 4;

}

System.out.println(number);

1
3
- [x]  5
Nothing is printed
_____________________________________________________________________________________


- 9. 

Why is there a need to use try-catch blocks?
1. To achieve security

2. To handle exceptions in the code

3. To write unit tests

4. To fix an issue

The are 1 correct answers

- [x]  2
2,3,5
1
4
2, 3
1,2






_____________________________________________________________________________________



- 10. 

The finally block is executed in which of the following cases? Choose all the below statements that satisfies the question.
1. When an exception does not occur

2. When an exception occurr but not handled by the catch block

3. When an exception occurs and is handled by the catch block

The are 1 correct answers

Only 1
1,2
2,3
Only 3
Only 2
- [x]  1,2,3




_____________________________________________________________________________________



- 11. 
Will the below program throw an exception? If yes then what type of exception it will throw?







public class Main{

public static void main(String[] args) {
try
{
    boolean data = (0/0 == 0);
}
catch(ArithmeticException e)
{
    System.out.println(e);
}

}
}

NullPointerException
InterruptedException
ClassNotFoundException
NoSuchMethodException
The program will not throw any exception
- [x]  ArithmeticException




_____________________________________________________________________________________



- 12. 


Which statement is true about exception handling?

The are 1 correct answers

- [x] At least one catch block must accompany a try statement
All statements in a try block are executed, even if an exception occurs in the middle of the try block
At least one statement in a try block must throw an exception
All catch blocks must be ordered from general to most specific





_____________________________________________________________________________________


